#!/usr/bin/env python3
"""
apply_atmos_corrections.py - run tropospheric and ionospheric corrections
*after* all interferograms have been generated by run_pair_conda_new.py.

Typical use
-----------
# one specific pair directory
python 3_do_orrections_tuning.py /mnt/DATA2/bakke326l/processing/tuning/path150_20071216_20080131_ra2_az5_filter0.6

# every pair directory under .../processing/tuning
python 3_do_corrections_tuning.py --batch /mnt/DATA2/bakke326l/processing/tuning
"""
from __future__ import annotations
import argparse, subprocess, sys
from pathlib import Path

import numpy as np, rasterio, matplotlib.pyplot as plt
from matplotlib import colormaps

from help_atm_correction import do_iono_correction, do_tropo_correction

# ---------------------------------------------------------------------- paths
BASE       = Path(__file__).resolve().parents[1]           # ~/InSAR/main
TROPO_DIR  = BASE / "data" / "aux" / "tropo"
HOME_PROC  = BASE / "processing"

# ----------------------------------------------------------------- utilities
def quicklook_png(src: Path, dst: Path, band: int = 1) -> None:
    """Plot one band and save as PNG."""
    turbo = colormaps.get_cmap("turbo")
    with rasterio.open(src) as ds:
        arr = ds.read(band, masked=True)
    vmin, vmax = np.percentile(arr.compressed(), [1, 99])
    norm = np.clip((arr - vmin) / (vmax - vmin), 0, 1)
    rgba = (turbo(norm.filled(0)) * 255).astype(np.uint8)
    plt.imsave(dst, rgba[..., :3])         # drop alpha channel

def translate(src: Path, dst: Path) -> None:
    subprocess.check_call(["gdal_translate", "-of", "GTiff", str(src), str(dst)])

def parse_combo(pairdir: Path) -> tuple[int, int, float]:
    """
    Parse ra/az/alpha from folder name like:
    path150_20071216_20080131_ra10_az16_filter0.6
    """
    toks = pairdir.name.split("_")
    ra = int(next(t[2:] for t in toks if t.startswith("ra")))
    az = int(next(t[2:] for t in toks if t.startswith("az")))
    fil = float(next(t[len("filter"):] for t in toks if t.startswith("filter")))
    return ra, az, fil

def parse_dates(pairdir: Path) -> tuple[str, str]:
    """
    Extract reference & secondary dates from a directory name:
    path150_20071216_20080131_ra2_az5_filter0.6
                  ^ref      ^sec
    """
    toks = pairdir.name.split('_')
    if len(toks) < 3:
        raise ValueError(f"Cannot parse dates from {pairdir.name}")
    return toks[1], toks[2]

    
# ------------------- LOS→vertical displacement (cm) writer -------------------
def make_vertical_cm_from_corrected(pairdir: Path) -> Path | None:
    """
    Convert tropo+iono corrected unwrapped phase (radians) to **vertical displacement (cm)**
    using the same method as the tropospheric correction:
      - incidence is read from geometry/los.rdr.geo.vrt, band 1, in **degrees**
      - vertical = - d_LOS / cos(inc)
      - d_LOS = (λ / 4π) * phase  with fixed λ = 0.2362 m
    """
    WAVELENGTH = 0.2362  # meters

    igram_dir = pairdir / "interferogram"
    inspect_dir = pairdir / "inspect"
    geom_dir  = pairdir / "geometry"

    # 1) corrected unwrapped phase (radians) — band 2
    src = igram_dir / "filt_topophase_tropo_iono.unw.geo"
    if not src.exists():
        print(f"⚠️  {src} does not exist")
        return None
    with rasterio.open(src) as ds:
        phase = ds.read(1).astype(np.float32)   # radians
        profile = ds.profile

    # 2) incidence angle (degrees) from geometry/los.rdr.geo.vrt, band 1
    inc_path = geom_dir / "los.rdr.geo.vrt"
    if not inc_path.exists():
        inc_path = geom_dir / "los.rdr.geo"     # light fallback to the raw .geo if VRT missing
    with rasterio.open(inc_path) as ds_inc:
        inc_deg = ds_inc.read(1).astype(np.float32)  # degrees
    inc = np.deg2rad(inc_deg)                        # radians
    cosi = np.cos(inc).astype(np.float32)

    # 3) LOS displacement (m) from phase; then vertical (cm)
    d_los_m  = (WAVELENGTH / (4.0 * np.pi)) * phase
    d_vert_m = np.full_like(d_los_m, np.nan, dtype=np.float32)
    safe = np.abs(cosi) > 1e-6
    d_vert_m[safe] = - d_los_m[safe] / cosi[safe]    # same convention as tropo: divide by cos(inc)
    d_vert_cm = d_vert_m * 100.0

    # 4) write GeoTIFF
    ref, sec   = parse_dates(pairdir)
    out = inspect_dir / f"vertical_displacement_cm_{ref}_{sec}.geo.tif"
    prof = profile.copy()
    prof.update({
        "driver": "GTiff",
        "count": 1,
        "dtype": "float32",
        "nodata": np.float32(np.nan),
        "compress": "deflate",
        "predictor": 3,
        "zlevel": 6,
    })
    with rasterio.open(out, "w", **prof) as dst:
        dst.write(d_vert_cm, 1)

    print(f"💾 Wrote vertical displacement (cm): {out}")
    # quicklook
    try:
        png = HOME_PROC / "inspect" / f"{out.stem}.png"
        quicklook_png(out, png, band=1)
    except Exception as e:
        print(f"⚠️  Quicklook failed: {e}")

    return out

# ------------------------------------------------------------ main workflow
def process_pair(pairdir: Path) -> None:
    ref, sec   = parse_dates(pairdir)
    range_looks, az_looks, filter = parse_combo(pairdir)
    
    igram_dir  = pairdir / "interferogram"
    tropo_dir  = pairdir / "troposphere"
    tropo_dir.mkdir(exist_ok=True)
    inspect_dir = pairdir / "inspect"
    inspect_dir.mkdir(exist_ok=True)

    print(f"😶‍🌫️  Tropospheric correction → {pairdir.name}")
    do_tropo_correction(wdir=pairdir, ref=ref, sec=sec,
                        gacos_dir=TROPO_DIR, tropo_dir=tropo_dir)

    print("🌌  Ionospheric correction")
    do_iono_correction(work_dir=pairdir, out_dir=igram_dir)

    suffix = f"{ref}_{sec}_ra{range_looks}_az{az_looks}_filter{filter}"

    translate_list = [
        igram_dir / "filt_topophase_tropo.unw.geo",
        igram_dir / "filt_topophase_tropo_iono.unw.geo",
        igram_dir / "filt_topophase_tropo_iono_wrapped.unw.geo",
        tropo_dir  / f"{ref}_{sec}.aps.geo",
    ]

    for src in translate_list:
        if not src.exists():
            continue
        tif = inspect_dir / f"{src.name}{suffix}.tif"
        translate(src, tif)
        png = HOME_PROC / "inspect" / f"{src.stem}{suffix}.png"
        quicklook_png(src, png)

    print(f"✅  Atmospheric corrections complete for {pairdir}\n")

    # Vertical displacement (cm) with same incidence handling as tropo
    make_vertical_cm_from_corrected(pairdir)

    print(f"✅  All corrections complete for {pairdir}\n")

def collect_pairs(root: Path) -> list[Path]:
    return [d for d in root.iterdir() if d.is_dir() and d.name.startswith("path")]

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("pairdir", nargs="*", type=Path,
                    help="One or more individual pair directories")
    ap.add_argument("--batch", type=Path,
                    help="Root folder that contains many pair directories")
    args = ap.parse_args()

    targets: list[Path] = []
    if args.batch:
        targets.extend(collect_pairs(args.batch))
    targets.extend(args.pairdir)

    if not targets:
        sys.exit("Nothing to do, supply one or more pair dirs or --batch")

    for p in targets:
        process_pair(p.resolve())

if __name__ == "__main__":
    main()
